version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"

  postgres-db:
    image: postgres:16.1-alpine
    container_name: postgres
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
      - redis
      - nginx

  react:
    build:
      context: ../pcost-frontend
      dockerfile: ../pcost-frontend/Dockerfile
    container_name: react
    ports:
      - "5173:5173"
    depends_on:
      - fastapi
      - nginx

  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    ports:
      - "6379:6379"