version: '3.8'

services:
  postgres-db:
    image: postgres:16.1-alpine
    container_name: postgres
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
